Sprint 6 solution
igor2141/java-kanban pull request #3
Opened 2024-09-04 11:48 UTC by igor2141

2024-09-05 16:56 UTC, mikita95 requested changes
По заданию нужно реализовать свою версию списка

2024-09-05 16:56 UTC, mikita95 commented on src/service/InMemoryHistoryManager.java
> +    Set<Task> history = new LinkedHashSet<>();
Не хватает модификатора доступа.

А также по заданию нужно реализовать свою версию списка

2024-09-18 20:56 UTC, TyutterinYakov reviewed
Добрый вечер! В целом - хорошо) Отметил то, что следует исправить и то, что можно сделать лучше) Хорошего вечера! Если возникнут вопросы по ревью - пиши в пачку, буду рад помочь🌃

2024-09-18 20:56 UTC, TyutterinYakov commented on src/service/InMemoryTaskManager.java
>      public void deleteTask(int id) {
Не забываем также удалить задачу из истории при ее удалении)

Аналогично с другими методами, где осуществляется удаление задач/подзадач/эпиков)

2024-09-18 20:56 UTC, TyutterinYakov commented on src/service/InMemoryTaskManager.java
>          historyManager.historyAdd(tasks.get(id));
Можно было бы ввести переменную/константу для полученного значения из мапы, чтобы не дублировать код и обращение к хранилищу)
```
final Task task = tasks.get(id);
historyManager.historyAdd(task);
return task;
```
Аналогично с другими методами ниже)

2024-09-18 20:56 UTC, TyutterinYakov commented on src/service/InMemoryTaskManager.java
>      public void clearTasks() {
Не забываем также удалить все задачи из истории)

2024-09-18 20:56 UTC, TyutterinYakov commented on src/service/Managers.java
>  public class Managers {
(предложение) Так как класс не имеет состояния(все `static`), значит создание объектов этого класса не имеет смысла. Можно объявить в нем приватный конструктор без параметров, чтобы избежать создания бессмысленных объектов этого класса. Это тонкость, которую хорошо было бы понять) То есть - если у класса нет публичного конструктора - создание объекта этого класса невозможно(ну почти, в java есть некоторый механизм, который может помочь это обойти, но об этом позже)) Когда ты создаешь класс, в нем по дефолту есть публичный конструктор без параметров, который в коде не видно, но он есть. Если мы создаем приватный, мы его перекрываем, а значит запрещаем создавать объекты этого класса

2024-09-18 20:56 UTC, TyutterinYakov commented on src/service/Node.java
> +class Node<T> {
Для соблюдения инкапсуляции - поля класса должны быть приватными, а для доступа к ним следует использовать геттеры и сеттеры) Но также можно было бы представить его в виде внутреннего приватного и статического класса внутри менеджера истории, так как он используется лишь для его внутренней реализации) Тогда геттеры/сеттеры не потребуются)
https://docs.oracle.com/javase/tutorial/java/javaOO/nested.html

2024-09-18 20:56 UTC, TyutterinYakov commented on src/service/InMemoryHistoryManager.java
> +    class CustomLinkedList<T> {
Так как класс используется лишь для внутренней реализации - следует сделать его приватным) Также лучше расположить его в конце класса, чтобы сразу был виден предоставляемый API, а затем уже приватные - внутренняя реализация). Таким образом будет проще извлекать информацию из кода и ориентироваться по нему

2024-09-18 20:56 UTC, TyutterinYakov commented on src/service/InMemoryHistoryManager.java
Отсутствует метод удаления задачи из истории по идентификатору

2024-09-18 20:56 UTC, TyutterinYakov commented on src/service/InMemoryHistoryManager.java
> +    public void removeNode(Node node) {
Этот метод должен находиться внутри `CustomLinkedList`, так как это часть его реализации)

2024-09-18 20:56 UTC, TyutterinYakov commented on src/service/InMemoryHistoryManager.java
> +        if (nodes.containsKey(task.getId())) {
Кажется, что логику можно было бы записать более кратко)
Например:
```
remove(task.getId());
history.addLast(task);
```
А саму логику по удалению/добавлению расположить в вызываемых методах, так как они отвечабт за этот функционал)

2024-09-18 20:56 UTC, TyutterinYakov commented on src/service/InMemoryHistoryManager.java
> +            List<T> tasks = new ArrayList<>();
Можно было бы использовать `LinkedList`, так как в нем операции вставки, с чем есть проблема у `ArrayList`, выполняются за O(1). Но можно выделить сразу требуемый размер(new `ArrayList<>(history.size()))` - это решит проблему вставки)
Будет очень полезно почитать про то, как работают методы этих классов, это спрашивают на собеседованиях и действительно пригождается в работе. https://www.javatpoint.com/difference-between-arraylist-and-linkedlist

2024-09-18 20:56 UTC, TyutterinYakov commented on src/service/InMemoryHistoryManager.java
> +    public void removeNode(Node node) {
Хорошо было бы проверить, что значение `node` не `null`, чтобы избежать NPE) А также, чтобы не дублировать эти проверки в других местах

2024-09-18 20:56 UTC, TyutterinYakov commented on src/service/InMemoryHistoryManager.java
> +    public void removeNode(Node node) {
Не учитывается вариант, когда мы удаляем последний узел из списка) То есть тот, что одновременно и хвост, и голова списка)

2024-09-18 20:56 UTC, TyutterinYakov commented on src/service/InMemoryHistoryManager.java
> +            }
Здесь также можно было бы еще произвести добавление в мапу)

2024-09-19 19:33 UTC, TyutterinYakov reviewed
Добрый вечер! Отметил оставшиеся недочеты) Хорошего вечера! Если возникнут вопросы по ревью - пиши в пачку, буду рад помочь🌃

2024-09-19 19:33 UTC, TyutterinYakov commented on src/service/InMemoryTaskManager.java
> +        for (Integer i: subtasks.keySet()) {
Лучше назвать переменные более осмысленно, чтобы по названию уже было понятно, что она хранит)
Аналогично в других местах

2024-09-19 19:33 UTC, TyutterinYakov commented on src/service/InMemoryTaskManager.java
>          for (Integer i : epics.keySet()) {
Можно было бы итерировать по значения мапы - `.values()`, чтобы на каждой итерации лишний раз не обращаться к мапе)

2024-09-19 19:33 UTC, TyutterinYakov commented on src/service/InMemoryHistoryManager.java
> +        history.removeNode(history.nodes.get(id));
`removeNode(nodes.remove(task.getId()));`
Метод `remove` отработает как `get`, но дополнительно будет произведено удаление)

2024-09-19 19:33 UTC, TyutterinYakov commented on src/service/InMemoryHistoryManager.java
> +            if (nodes.containsKey(task.getId())) {
Можно было бы разместить сразу в начале метода, чтобы предварительно удалить старый узел, а потом уже производить добавление нового)
Условие не требуется, так как метод удаления уже содержит проверку на `null`

2024-09-19 19:33 UTC, TyutterinYakov commented on src/service/InMemoryHistoryManager.java
> +            if (!nodes.isEmpty()) {
Не требуется, так как при вызове метода `put` ниже значение в мапе уже будет заменено)

2024-09-19 19:33 UTC, TyutterinYakov commented on src/service/InMemoryHistoryManager.java
> +                nodes.remove(node.data.getId());
Не требуется, так как в методе, который вызывает `removeNode` уже происходит удаление из мапы)

2024-09-19 19:33 UTC, TyutterinYakov commented on src/service/InMemoryHistoryManager.java
> +                nodes.remove(node.data.getId());
Не требуется, так как в методе, который вызывает `removeNode` уже происходит удаление из мапы)

2024-09-19 19:33 UTC, TyutterinYakov commented on src/service/InMemoryHistoryManager.java
> +                nodes.replace(head.data.getId(), head);
Эта логика не требуется

2024-09-19 19:33 UTC, TyutterinYakov commented on src/service/InMemoryHistoryManager.java
> +                nodes.remove(node.data.getId());
Не требуется, так как в методе, который вызывает `removeNode` уже происходит удаление из мапы)

2024-09-19 19:33 UTC, TyutterinYakov commented on src/service/InMemoryHistoryManager.java
> +                nodes.replace(tail.data.getId(), tail);
Эта логика не требуется

2024-09-19 19:33 UTC, TyutterinYakov commented on src/service/InMemoryHistoryManager.java
> +                nodes.replace(nextNode.data.getId(), nextNode);
Эта логика не требуется

2024-09-19 19:33 UTC, TyutterinYakov commented on src/service/InMemoryHistoryManager.java
> +                nodes.replace(prevNode.data.getId(), prevNode);
Эта логика не требуется

2024-09-19 19:33 UTC, TyutterinYakov commented on src/service/InMemoryHistoryManager.java
> +                nodes.remove(node.data.getId());
Не требуется, так как в методе, который вызывает `removeNode` уже происходит удаление из мапы)

2024-09-20 05:34 UTC, TyutterinYakov approved these changes
Добрый день! Поздравляю с успешной сдачей спринта :) Сил и терпения на этом сложном, но интересном пути! Успехов в обучении и прекрасного дня!🌅🎇

2024-09-20 09:59 UTC, merged